### ISSUE TITLE
Visual studio project

### ISSUE THREAD

**Issue by voed** [Amaroq7/SPMod#62]
Meson has built-in VS project generator but its completely fucked up and needs a lot of fixes after generation. Why dont just create project once and add it to repository?

**Comment by Amaroq7** [comment]
This could be done, the only concern I have is those files could go easily out of date, since not everyone uses visual studio for development and the project is still in early development, so I expect lots of changes happen in those files. Sure they could be edited by hand but there's no guarantee that they'll be working properly. If there are people who use visual studio for building and are willing to keep an eye on those files whether they work as they should, I see no problem to add them.

**Comment by voed** [comment]
I can do that. But what about SPConfig file? Its generated by meson. When "commit sha" can be just replaced by static text(as long as its 3rd party user build), version is hardcoded in meson.build.
Maybe we can create some version file?

**Comment by Amaroq7** [comment]
Version and commit sha could be hardcoded in f.e. `msvc20xx/SPConfig.hpp`. I'd also add some define like `SP_USE_MSVC_CUSTOM_VERSION` to include appropriate `SPConfig.hpp`.
